#ifdef CONFIG_OPPO_SECURE_GUARD
#Yi.Zhang@Security, 2020-04-08, Add for prevent root check
obj-$(CONFIG_OPPO_ROOT_CHECK)	 +=  oppo_root_check.o
obj-$(CONFIG_OPPO_EXECVE_BLOCK)	 +=  oppo_exec_block.o
obj-$(CONFIG_OPPO_MOUNT_BLOCK)	 +=  oppo_mount_block.o
obj-$(CONFIG_OPPO_SECURE_GUARD)	 +=  oppo_guard_general.o
obj-$(CONFIG_OPPO_SECURE_GUARD)	 +=  oppo_hook_syscall.o
#endif /* CONFIG_OPPO_SECURE_GUARD */