#ifdef CONFIG_OPPO_SECURE_GUARD
#Yi.Zhang@Security, 2020-04-08, Add for kevent upload
obj-$(CONFIG_OPPO_KEVENT_UPLOAD) += oppo_kevent_upload.o
obj-$(CONFIG_OPPO_KEVENT_TEST)   += oppo_kevent_test.o
#endif /* CONFIG_OPPO_SECURE_GUARD */