# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel block layer
#

#ifdef VENDOR_EDIT
#/*Huacai.Zhou@BSP.Kernel.IO, 2020-06-12,add ux io first opt*/
obj-y	+= oppo_uxio_first_opt.o oppo_high_prio_task.o
#endif
