obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  device_info/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  project_info/
obj-$(CONFIG_OPPO_HYPNUS)     +=  oppo_hypnus/
obj-y +=  oppo_healthinfo/
obj-$(CONFIG_RECORD_MDMRST)	+=  mdmrst/
obj-y +=  sensor/
obj-y +=  oppo_kevent_feedback/

#Liang.Zhang@TECH.Storage.Stability.OPPO_SHUTDOWN_DETECT, 2019/04/28, Add for shutdown detect
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)  +=  oppo_shutdown_detect/

#Yajie.chen@Tech.BSP.Sensor,2018/10/18, Add for SLPI Monitor
obj-$(CONFIG_RECORD_SLPIRST)	+=  oppo_slpirst/
#Kun.Hu@TECH.BSP.Stability.PHOENIX_PROJECT 2019/06/15, Add for PHOENIX_PROJECT
obj-$(CONFIG_OPPO_PHOENIX)     +=  oppo_phoenix/

#ifdef VENDOR_EDIT
#linzhangru@PSW.TECH, 2019/11/30, Add for sau power key detection
obj-$(CONFIG_OPPO_SAUPWK) += oppo_saupwk/
#endif /* VENDOR_EDIT */

