# ifdef OPLUS_FEATURE_SENSOR_CRASH_MONITOR
# yajie.chen@BSP.Driver, 2019/10/18, Add for slpi crash reason
obj-$(CONFIG_OPLUS_FEATURE_SENSOR_CRASH_MONITOR)	+=  oppo_slpirst.o
# endif /* VENDOR_EDIT */
