#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3658U) += focal_drivers_ft3658u.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3658U) += focal_test_ft3658u.o
