#Yang.Gang@TECH.BSP.Stability.THEIA_PROJECT 2020/06/15, Add for THEIA_PROJECT
ifeq ($(CONFIG_OPLUS_FEATURE_THEIA),y)
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += oppo_BScheck.o
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += oppo_brightscreen_check.o
endif
